import { PrismaClient } from '@prisma/client'
import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

const questions = [
  {
    text: "Which of the following statements with regard to genetic medicines is/are correct?\nGenetic medicines correct/compensate for the faulty genes responsible for disease.\nEngineered viruses and lipid nanoparticles are used as carriers of the genetic medicine.\nGenetic medicines alter the entire DNA sequence.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "c"
  },
  {
    text: "Which of the following statements with regard to Large Language Models (LLMs) used in machine learning is/are correct?\nLLMs assign probabilities to the next possible words and then pick the one with the highest probability.\nLLMs process data through mathematical optimization to minimise prediction errors.\nLLMs produce unbiased outputs.",
    optionA: "(a) 1 only",
    optionB: "(b) 1 and 2 only",
    optionC: "(c) 2 and 3 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "b"
  },
  {
    text: "Which of the following statements with regard to stealth technology is/are correct?\nStealth objects have a very small radar cross-section and are coated with Radar Absorbing Material.\nStealth objects can be detected using specific frequencies.\nStealth objects are coated with metamaterials to increase the scattering of electromagnetic radiation.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "b"
  },
  {
    text: "Which of the following statements with regard to Black Boxes used in modern aircraft is/are correct?\nThey carry a beacon emitting red light pulses to facilitate underwater detection.\nThey record both the cockpit voice and flight data.\nTheir memory units are made using either stainless steel or titanium.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "d"
  },
  {
    text: "Which of the following statements with regard to Green Hydrogen is/are correct?\nIt is decarbonized hydrogen obtained from natural gas reforming combined with carbon capture and storage (CCS).\nIt is produced using electrolysis of water with electricity generated by renewable energy.\nNational Green Hydrogen Mission of India aims for abatement of nearly 50 MMT of annual greenhouse gas emissions by 2030.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "b"
  },
  {
    text: "Consider the following statements with regard to involvement of private entities in India's space programme:\nThe Indian National Space Promotion and Authorisation Centre (IN-SPACe) is an autonomous agency formed to facilitate participation of private entities.\nAgnikul Cosmos launched the world's first flight using a 3D-printed rocket engine.\nSkyroot Aerospace has developed liquid fuel for GSLV.\nWhich of the statements given above is/are correct?",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "c"
  },
  {
    text: "Which of the following statements with regard to drone swarms is/are correct?\nThey use Terahertz band of frequency to communicate with the command centre.\nIndividual drones in the swarm can communicate with other drones in the swarm.\nGPS Spoofing is a commonly used technique to counter drone swarm attack.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "c"
  },
  {
    text: "Which of the following statements with regard to GenomeIndia Project is/are correct?\nIt is a part of the Human Genome Project.\nThe project is funded by the Department of Biotechnology (DBT), Government of India.\nIts primary aim is to build a catalogue of genetic diversity of the Indian population.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "d"
  },
  {
    text: "Which of the following statements with regard to the National Quantum Mission (NQM) is/are correct?\nIt aims at developing intermediate-scale quantum computers with 50–1000 physical qubits.\nIts implementation includes setting up four Thematic Hubs (T-Hubs) in academic and national R&D institutes across India.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 only",
    optionC: "(c) Both 1 and 2",
    optionD: "(d) Neither 1 nor 2",
    correctAnswer: "b"
  },
  {
    text: "Which of the following statements with regard to India's Deep Ocean Mission is/are correct?\nIt was launched by the Ministry of Ports, Shipping and Waterways, Government of India.\nMatsya-6000 has been designed to carry 3 people for deep sea exploration.\nSamudrayaan is a project under this mission.",
    optionA: "(a) 1 only",
    optionB: "(b) 2 and 3 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "b"
  },
  {
    text: "Mr. X, a senior officer, was overseeing a critical vaccination programme during a pandemic...\nWhich one among the following principles of public administration was most strongly demonstrated by Mr. X's actions?",
    optionA: "(a) Esprit de corps",
    optionB: "(b) Equity",
    optionC: "(c) Accountability",
    optionD: "(d) Delegation",
    correctAnswer: "c"
  },
  {
    text: "In a multi-ethnic district where both economic competition and historical grievances...\nWhich of the following statements would contribute to the resolution process?\nA successful conflict resolution process must begin by acknowledging the cultural concerns...\nThe Government should move ahead with the project...\nCreate a multi-stakeholder dialogue platform...\nConduct an independent Environmental and Social Impact Assessment (ESIA)...",
    optionA: "(a) 1, 3 and 4 only",
    optionB: "(b) 2, 3 and 4 only",
    optionC: "(c) 1 and 2 only",
    optionD: "(d) 1, 2, 3 and 4",
    correctAnswer: "a"
  },
  {
    text: "Ms. X is a mid-level civil service official working in the urban development department...\nWhat amongst the following should Ms. X do now?\nImmediately disclose the information to the project committee and the public.\nRecommend removing the contractor from the shortlist.\nPropose a limited disclosure to an oversight committee while keeping the information confidential from the public for the time being.",
    optionA: "(a) 1 and 2 only",
    optionB: "(b) 3 only",
    optionC: "(c) 2 and 3 only",
    optionD: "(d) 1, 2 and 3",
    correctAnswer: "d"
  },
  {
    text: "'X' was addressing a seminar on the meaning of the term \"law\"...\nSelect the correct conclusion:",
    optionA: "(a) 'X' is correct...",
    optionB: "(b) The view of 'Y'...",
    optionC: "(c) The views of both 'X' and 'Y' are correct.",
    optionD: "(d) The view of only 'Y' is correct.",
    correctAnswer: "b"
  },
  {
    text: "Consider the following statements with reference to the Constitution of India...",
    optionA: "(a) All three statements are correct.",
    optionB: "(b) There is no correct statement.",
    optionC: "(c) There are two correct statements that include statement 3.",
    optionD: "(d) There is only one correct statement.",
    correctAnswer: "b"
  },
  {
    text: "Which of the following statements with regard to the persons with disabilities in India is/are correct?\nThe Rights of Persons with Disabilities Act...\nThe Sugamya Bharat Abhiyan...\nThe National Divyangjan Finance and Development Corporation...",
    optionA: "(a) 1 and 2",
    optionB: "(b) 2 only",
    optionC: "(c) 1 and 3",
    optionD: "(d) 1 only",
    correctAnswer: "a"
  },
  {
    text: "Consider the following statements about provisions pertaining to the Scheduled Castes and the Scheduled Tribes in India...",
    optionA: "(a) There are two correct statements, that include statement 2.",
    optionB: "(b) There are two correct statements, that are statements 1 and 3.",
    optionC: "(c) There is only one correct statement.",
    optionD: "(d) All three statements are correct.",
    correctAnswer: "a"
  },
  {
    text: "Consider the following statements in respect of questions asked by the Members in the Parliament of India...",
    optionA: "(a) All the three statements are correct.",
    optionB: "(b) There are two correct statements, that include statement 2.",
    optionC: "(c) There is only one correct statement.",
    optionD: "(d) There is no correct statement.",
    correctAnswer: "c"
  },
  {
    text: "Consider the following statements about the Welfare of Scheduled Castes and Scheduled Tribes Committee of the Parliament of India...",
    optionA: "(a) There are four correct statements.",
    optionB: "(b) There is only one correct statement, that is statement 2.",
    optionC: "(c) There are two correct statements, that include statement 1.",
    optionD: "(d) There is no correct statement.",
    correctAnswer: "d"
  },
  {
    text: "Consider the following statements about Mission Sudarshan Chakra of India...\nIt aims to enhance India's air defence...\nIt is being designed to enhance rapid, precise...\nOne of the aims is to cover all public places by an expanded nationwide security shield by 2035.",
    optionA: "(a) 1, 2 and 3",
    optionB: "(b) 1 and 2 only",
    optionC: "(c) 2 and 3 only",
    optionD: "(d) 1 only",
    correctAnswer: "a"
  }
];

async function main() {
  console.log('Start seeding batch 3...');
  let i = 0;
  for (const q of questions) {
    const question = await prisma.question.create({
      data: q,
    });
    i++;
    console.log(`Created question with id: ${question.id}`);
  }
  console.log(`Seeding finished. Inserted ${i} questions.`);
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
