import 'dotenv/config'
import { PrismaClient } from '@prisma/client'
import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

type Letter = 'A' | 'B' | 'C' | 'D'

function opts(a: string, b: string, c: string, d: string, correct: Letter) {
  const raw = { A: a, B: b, C: c, D: d }
  return (['A', 'B', 'C', 'D'] as Letter[]).map((label) => ({
    label,
    text: raw[label],
    isCorrect: label === correct,
  }))
}

interface SeedQuestion {
  category: string
  text: string
  options: { label: Letter; text: string; isCorrect: boolean }[]
}

// NOTE: Q52-Q55 and a few List-I/List-II items were truncated with "..." in the
// source document the client pasted (scenario/case-study questions and match-the-column
// tables got cut off). They are seeded verbatim as provided; fill in the full statement
// text from the original PDF/Word doc before using these in a live quiz.
const questions: SeedQuestion[] = [
  { category: 'Art & Culture', text: "Which one of the following Carnatic music ragas is similar to Raga Bilawal in Hindustani music?", options: opts('Nat Bhairavi', 'Kamavardhini', 'Hanumatodi', 'Dheera Shankarabharanam', 'D') },
  { category: 'History', text: "The artificially fixed rupee-sterling exchange rate prescribed by the Hilton-Young Commission (1926) was adopted by the British Government for which one of the following reasons?", options: opts("Aiding the flow of remittances from India and maintaining India's creditworthiness", 'Providing support to Indian importers', 'Encouraging export of cotton produce from India', 'Preventing depreciation of the Rupee in terms of gold', 'A') },
  { category: 'History', text: "Consider the following statements:\nI. Pali texts contain the first definite references to coins, e.g., kahapana, nikkha, kamsa and kakanika.\nII. The literary evidence from Pali texts is corroborated by archaeological evidence of punch-marked coins from many sites, most of them made of silver.\nThe above statements have been associated with which of the following?\n1. Emergence of urban life\n2. Transition to money economy\nChoose the correct answer:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'C') },
  { category: 'Art & Culture', text: "Which of the following temples has/have a Nagara-style shikhara?\n1. Malegitti Shivalaya, Badami\n2. Huchimalligudi Temple, Aihole\n3. Dashavatara Temple, Deogarh\n4. Virupaksha Temple, Pattadakal\nSelect the correct answer using the code below:", options: opts('1 and 2', '2 and 3', '3 only', '3 and 4', 'C') },
  { category: 'Art & Culture', text: "Among the four main forms of existence of life recognized in Jainism, which one of the following is not included?", options: opts('Deva (gods)', 'Yaksha (demi-gods)', 'Manushya (humans)', 'Tiryancha (animals and plants)', 'B') },
  { category: 'History', text: "Consider the following statements regarding the Gupta period:\n1. The Allahabad Pillar Inscription describes the conquests of Samudragupta.\n2. The Allahabad Pillar Inscription was composed by Harisena.\n3. Chandragupta II assumed the title \"Vikramaditya.\"\nWhich of the statements given above are correct?", options: opts('1 and 2 only', '2 and 3 only', '1 and 3 only', '1, 2 and 3', 'D') },
  { category: 'History', text: "With reference to the Vijayanagara Empire, consider the following statements:\n1. Domingo Paes visited the Vijayanagara Empire during the reign of Krishnadevaraya.\n2. Abdur Razzaq visited Vijayanagara during the reign of Devaraya II.\n3. The Battle of Talikota was fought in 1565.\nWhich of the statements given above are correct?", options: opts('1 and 2 only', '2 and 3 only', '1 and 3 only', '1, 2 and 3', 'D') },
  { category: 'History', text: "Consider the following statements regarding the Indian National Congress:\n1. The first session of the Indian National Congress was held at Bombay in 1885.\n2. W.C. Bonnerjee was the first President of the Indian National Congress.\n3. Allan Octavian Hume played an important role in the formation of the Congress.\nWhich of the statements given above are correct?", options: opts('1 and 2 only', '2 and 3 only', '1 and 3 only', '1, 2 and 3', 'D') },
  { category: 'History', text: "Which one of the following pairs is correctly matched?\nMovement — Leader\nA. Bardoli Satyagraha — Vallabhbhai Patel\nB. Champaran Satyagraha — Bal Gangadhar Tilak\nC. Kheda Satyagraha — Jawaharlal Nehru\nD. Moplah Rebellion — Subhas Chandra Bose", options: opts('A only', 'A and B only', 'A and C only', 'B and D only', 'A') },
  { category: 'Polity & Governance', text: "Consider the following statements:\n1. The Directive Principles of State Policy are enforceable by courts.\n2. Fundamental Duties were added to the Constitution by the 42nd Constitutional Amendment.\n3. The Right to Education is a Fundamental Right.\nWhich of the statements given above are correct?", options: opts('2 and 3 only', '1 and 2 only', '1 and 3 only', '1, 2 and 3', 'A') },
  { category: 'Geography', text: "Consider the following assertion:\nIn the Pleistocene period either the Yamuna once flowed into the Indus, or the Sutlej flowed into the Yamuna and one major tributary of either had shifted from the Ganga to the Indus or vice versa.\nWhich of the following is/are the basis of the above assertion?\n1. The Nadi-Sukta of the Rigveda\n2. The explorations of the Sutlej and the Yamuna by Robert Bruce Foote\n3. The presence of the same species of dolphins in both the Indus and the Ganga river systems\nSelect the answer using the code given below:", options: opts('1 only', '2 only', '1 and 2', '3', 'A') },
  { category: 'Art & Culture', text: "What does an empty seat represent in early Buddhist iconography?", options: opts('The meditation of the Buddha', "The Buddha's First Sermon", "The Buddha's Mahaparinibbana", "The Buddha's Mahabhinishkramana", 'A') },
  { category: 'Geography', text: "Which of the following pairs of ancient and modern names of rivers is/are correctly matched?\n1. Vitasta — Chenab\n2. Asikni — Jhelum\n3. Parushni — Ravi\n4. Yayavati — Beas\nSelect the answer using the code given below:", options: opts('1 and 2', '3 and 4', '3 only', '4 only', 'C') },
  { category: 'Art & Culture', text: "Which of the following statements on the Amaravati Stupa and its relief sculpture is/are correct?\n1. It was located in the lower Krishna valley.\n2. In India, it was next only to the Sanchi Stupa in size.\n3. The Amaravati school of sculpture made a lasting impact on the later South Indian sculpture, and its products were carried to Sri Lanka and South-East Asia.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 3 only', '2 and 3 only', '1, 2 and 3', 'B') },
  { category: 'History', text: "Which of the following pairs of the king and his dynasty in early historical Tamilakam is/are not correctly matched?\n1. Senguttuvan — Chera\n2. Udayanjeral — Chola\n3. Nedunjeliyan — Pandya\nSelect the answer using the code given below:", options: opts('1 and 2', '2 only', '1 and 3', '3 only', 'B') },
  { category: 'History', text: "Which of the following factors contributed to the formation of the Forward Bloc by Subhas Chandra Bose in 1939?\n1. Bose failed to win the confidence of Mahatma Gandhi.\n2. The Congress Left was disunited and failed to support Bose.\n3. The Communists did not support Bose in his endeavours.\n4. The supporters of M. N. Roy and socialist leaders like Jayaprakash Narayan preferred Congress unity to supporting Bose.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '1, 2 and 4', '1, 3 and 4', '2 and 4 only', 'B') },
  { category: 'History', text: "Consider the following statements regarding the British policy in Awadh immediately after its annexation in 1856:\n1. The taluqdars were dispossessed of their estates but allowed to retain their arms and forts.\n2. A Summary Revenue Settlement was made in 1856 assuming that the taluqdars were outsiders.\n3. The British believed in taking revenue directly from the peasants by removing the taluqdars.\nWhich of the statements given above is/are correct?", options: opts('2 and 3 only', '1 and 3 only', '1, 2 and 3', '2 only', 'A') },
  { category: 'History', text: "Consider the following assertion:\nThe genesis of political alliances based on community lay in the very nature of the Montagu-Chelmsford Reforms, 1919.\nWhich of the following statements support/supports the above assertion?\n1. Reforms retained and extended the principle of separate electorates.\n2. Separate electorates were supposed to counter Indian nationalism, which was growing stronger.\n3. Deprived classes rallied around the favours inherent in separate electorates.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'C') },
  { category: 'Art & Culture', text: "Pandit Mallikarjun Mansur, the famous classical singer from Karnataka, represented the:", options: opts('Agra Gharana', 'Gwalior Gharana', 'Patiala Gharana', 'Jaipur-Atrauli Gharana', 'D') },
  { category: 'History', text: "In which one among the following texts does the term kshetra-patni (mistress of the field) originate?", options: opts('Rigveda', 'Atharvaveda', 'Ashtadhyayi', 'Arthashastra', 'C') },
  { category: 'Environment & Ecology', text: "Consider the following statements with reference to India's response to climate change:\nI. India's Long-Term Low Emission Development Strategy (LT-LEDS) is a crucial tool for achieving net-zero emissions by 2070.\nII. India's 4th Biennial Update Report (BUR-4) submitted in December, 2024 recorded around 8% decrease in Greenhouse gas emissions in 2020 over 2019.\nIII. Climate-resilient development necessarily depends on quick and short-term achievement of emission reduction targets.\nWhich of the following relationships among the above statements is/are correct?\n1. Statement I is empirically supported by Statement II.\n2. Statement III contradicts the approach implicit in Statement I.\n3. Statement I and Statement III together establish the premise of long-term sustainability.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'C') },
  { category: 'Environment & Ecology', text: "With respect to the Western Hoolock Gibbons, which of the following statements is/are correct?\n1. A Sanctuary in North-east India is home to this ape species listed as Endangered in the International Union for Conservation of Nature (IUCN) Red List.\n2. They have specialized brachiation and can easily swing between trees.\n3. They possess a strong and heavy build like gorillas, yet are remarkably agile tree climbers.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'B') },
  { category: 'Environment & Ecology', text: "Which of the following best explain(s) the rationale for protecting mangrove ecosystems in the context of climate resilience?\n1. Mangroves reduce tidal energy and store freshwater, making them ideal sites for paddy cultivation in saline estuarine belts.\n2. Their salt-sensitive roots filter seawater, making mangroves key to converting coastal land into freshwater aquaculture zones.\n3. By withstanding tidal surges and offering biomass resources, mangroves function both as natural bio-shields and livelihood bases for rural communities.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'D') },
  { category: 'Economy', text: "In what way(s) does the Vizhinjam International Seaport represent a structural shift in India's maritime trade and logistics policy?\n1. By functioning exclusively as a domestic cargo hub to reduce reliance on coastal shipping and eliminate the need for foreign collaborations.\n2. By focusing primarily on passenger cruise tourism and heritage shipping to increase Kerala's profile as a maritime heritage destination.\n3. By leveraging its natural deep draft and strategic location to reduce dependence on foreign trans-shipment ports, enhance revenue retention, and reposition India in regional maritime trade.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'D') },
  { category: 'Geography', text: "Identify the river of the Indian sub-continent on the basis of the following information:\n1. It has an antecedent drainage system.\n2. It flows through three countries.\n3. It originates in the Tibetan Plateau and is an important river for irrigation.\n4. It does not form distributaries.\nSelect the answer from the following:", options: opts('Brahmaputra', 'Indus', 'Sutlej', 'Teesta', 'C') },
  { category: 'Geography', text: "Which of the following with reference to Indian States is/are not correct?\n1. Uttar Pradesh shares its boundary with the highest number of other Indian States.\n2. Rajasthan shares the longest international border among all Indian States.\n3. Sikkim is the only State that shares its boundary with just one other Indian State.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'C') },
  { category: 'Environment & Ecology', text: "Which of the following statements with regard to the arrival of Amur Falcons at Doyang Lake in Nagaland each year from Mongolia is/are correct?\n1. It showcases how sustained local conservation efforts can contribute to the arrival and protection of international migratory birds.\n2. It reflects the global success of advanced tracking technologies that guide migratory birds back to their stopover sites.\n3. It confirms that Amur Falcons have adapted to permanent residency in India due to favourable habitat changes.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'A') },
  { category: 'Economy', text: "Which among the following is/are the objective(s) of the Rainfed Area Development (RAD) initiative under the National Mission for Sustainable Agriculture (NMSA)?\n1. Encouraging monoculture in rainfed areas\n2. Increasing rice cultivation in irrigated regions\n3. Enhancing productivity and minimising climatic risks through Integrated Farming Systems (IFS)\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'D') },
  { category: 'Economy', text: "Which of the following is/are the most significant implication(s) of obtaining Oeko-Tex certification for Eri Silk in the global textiles industry?\n1. It allows Indian exporters to compete in high-end markets that prioritise chemical-free products.\n2. It confirms that Eri Silk meets international safety, environmental and quality standards, enabling its entry into premium eco-conscious markets.\nSelect the correct answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'C') },
  { category: 'Geography', text: "Ships from which of the following countries have to cross the Strait of Hormuz to reach out to the Indian Ocean?\n1. Bahrain\n2. Syria\n3. Qatar\n4. Egypt\nSelect the correct answer using the code given below:", options: opts('1 and 2', '1 and 3', '2 and 3', '3 and 4', 'B') },
  { category: 'Geography', text: "Tungurahua Volcano, which was declared a Global Geopark by UNESCO in 2025, is situated in which one among the following countries?", options: opts('Ecuador', 'Peru', 'Bolivia', 'Colombia', 'D') },
  { category: 'Environment & Ecology', text: "With reference to Madhav National Park, which of the following statements is/are correct?\n1. It was declared a Tiger Reserve in India in 2025.\n2. Sakhya Sagar, which is designated as a Ramsar Site, is situated within this National Park.\n3. Its area is shared between Madhya Pradesh and Rajasthan.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'B') },
  { category: 'Geography', text: "With reference to the climate of Andaman and Nicobar Islands, which of the following statements is/are correct?\n1. The climate can be defined as a humid, tropical coastal climate.\n2. It receives rainfall from both South-west monsoon and North-east monsoon.\n3. Maximum precipitation is between December and May.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'D') },
  { category: 'Geography', text: "Which of the following geographical features or phenomena is/are associated with the Peninsular Block of India?\n1. Submergence of parts of the western coast due to tectonic activity.\n2. Presence of residual mountain ranges such as the Veliconda Hills and Mahendragiri Hills.\n3. Deep, V-shaped river valleys formed by fast-flowing rivers.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'B') },
  { category: 'Economy', text: "Consider the following statements with reference to the Sagarmala Programme of the Government of India:\nI. The Sagarmala Programme seeks to achieve port-led economic growth through cost-effective and sustainable coastal infrastructure.\nII. The success of the Sagarmala Programme is reflected in significant growth in coastal and inland waterway shipping, along with improved global port rankings.\nIII. Sagarmala 2.0 aims to position India as a global maritime innovation hub aligned with Atmanirbhar Bharat and Viksit Bharat 2047 visions.\nWhich of the following relationships among the above statements is/are correct?\n1. Statement II validates the effectiveness of the strategies envisioned in Statement I.\n2. Statement III extends the objectives of Statement I by embedding them into a future-oriented innovation framework.\n3. Statement I contradicts Statement III by focusing only on traditional infrastructure instead of modern innovation.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 2', '2 and 3', '3 only', 'B') },
  { category: 'Environment & Ecology', text: "Consider the following statements about Rhynchostylis retusa (Foxtail Orchid):\n1. It is an epiphytic orchid.\n2. The species is endemic to North-east India.\n3. It is the State flower of Arunachal Pradesh and Assam.\nWhich of the statements given above is/are correct?", options: opts('1 only', '1 and 3', '2 and 3', '3 only', 'A') },
  { category: 'Art & Culture', text: "Which one of the following statements with regard to the Moidams, built by the Tai-Ahom kingdom and inscribed as a World Heritage Site by UNESCO, is/are correct?\n1. They acted as army fortresses.\n2. They were recreation centres of the Royals and Nobles.\n3. They were burial grounds of the Royals and Nobles.\n4. They were battle drill centres of the Royals and Nobles.\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 3', '3 only', '2 and 4', 'C') },
  { category: 'Environment & Ecology', text: "At the United Nations Ocean Conference (UNOC) held in June 2025 in France, the Food and Agriculture Organization (FAO) of the United Nations demonstrated its leading voice on marine and ocean issues, especially on sustainable fisheries and aquaculture for resilient livelihood and \"Blue Transformation\".\nWhich of the following combinations about the \"Four Betters\" proposed by FAO for \"Blue Transformation\" is correct?", options: opts('Better production, better nutrition, better environment and better ocean', 'Better production, better nutrition, better environment and better life', 'Better coral reefs, better nutrition, better environment and better life', 'Better estuaries, better nutrition, better environment and better mangrove vegetation', 'B') },
  { category: 'Geography', text: "Which of the following statements with reference to Lake Turkana is/are correct?\n1. It is the largest desert lake in the world.\n2. The lake is situated in South Sudan along the eastern fringe of the Sahara Desert.\n3. The lake is listed as a UNESCO World Heritage Site and is also referred to as the \"Jade Sea\".\nSelect the correct answer using the code given below:", options: opts('1 only', '1 and 3 only', '2 and 3 only', '1, 2 and 3', 'B') },
  { category: 'Environment & Ecology', text: "Which one of the following is the first Plan Vivo certified Reducing Emissions from Deforestation and Forest Degradation (REDD+) project in India?", options: opts('Uttarakhand REDD+ project', 'ICFRE-ICIMOD Transboundary REDD+ project in North-Eastern Himalayas', 'Khasi Hills Community REDD+ project', 'Sikkim Mamley Kamrang Community REDD+ project', 'C') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to genetic medicines is/are correct?\n1. Genetic medicines correct/compensate for the faulty genes responsible for disease.\n2. Engineered viruses and lipid nanoparticles are used as carriers of the genetic medicine.\n3. Genetic medicines alter the entire DNA sequence.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'C') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to Large Language Models (LLMs) used in machine learning is/are correct?\n1. LLMs assign probabilities to the next possible words and then pick the one with the highest probability.\n2. LLMs process data through mathematical optimization to minimise prediction errors.\n3. LLMs produce unbiased outputs.\nSelect the answer using the code given below:", options: opts('1 only', '1 and 2 only', '2 and 3 only', '1, 2 and 3', 'B') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to stealth technology is/are correct?\n1. Stealth objects have a very small radar cross-section and are coated with Radar Absorbing Material.\n2. Stealth objects can be detected using specific frequencies.\n3. Stealth objects are coated with metamaterials to increase the scattering of electromagnetic radiation.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'B') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to Black Boxes used in modern aircraft is/are correct?\n1. They carry a beacon emitting red light pulses to facilitate underwater detection.\n2. They record both the cockpit voice and flight data.\n3. Their memory units are made using either stainless steel or titanium.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'D') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to Green Hydrogen is/are correct?\n1. It is decarbonized hydrogen obtained from natural gas reforming combined with carbon capture and storage (CCS).\n2. It is produced using electrolysis of water with electricity generated by renewable energy.\n3. National Green Hydrogen Mission of India aims for abatement of nearly 50 MMT of annual greenhouse gas emissions by 2030.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '2 only', '1, 2 and 3', 'B') },
  { category: 'Science & Technology', text: "Consider the following statements with regard to involvement of private entities in India's space programme:\n1. The Indian National Space Promotion and Authorisation Centre (IN-SPACe) is an autonomous agency formed to facilitate participation of private entities.\n2. Agnikul Cosmos launched the world's first flight using a 3D-printed rocket engine.\n3. Skyroot Aerospace has developed liquid fuel for GSLV.\nWhich of the statements given above is/are correct?", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'C') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to drone swarms is/are correct?\n1. They use Terahertz band of frequency to communicate with the command centre.\n2. Individual drones in the swarm can communicate with other drones in the swarm.\n3. GPS Spoofing is a commonly used technique to counter drone swarm attack.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'C') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to GenomeIndia Project is/are correct?\n1. It is a part of the Human Genome Project.\n2. The project is funded by the Department of Biotechnology (DBT), Government of India.\n3. Its primary aim is to build a catalogue of genetic diversity of the Indian population.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'D') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to the National Quantum Mission (NQM) is/are correct?\n1. It aims at developing intermediate-scale quantum computers with 50–1000 physical qubits.\n2. Its implementation includes setting up four Thematic Hubs (T-Hubs) in academic and national R&D institutes across India.\nSelect the answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'B') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to India's Deep Ocean Mission is/are correct?\n1. It was launched by the Ministry of Ports, Shipping and Waterways, Government of India.\n2. Matsya-6000 has been designed to carry 3 people for deep sea exploration.\n3. Samudrayaan is a project under this mission.\nSelect the answer using the code given below:", options: opts('1 only', '2 and 3 only', '1 and 2 only', '1, 2 and 3', 'B') },
  { category: 'Polity & Governance', text: "Mr. X, a senior officer, was overseeing a critical vaccination programme during a pandemic. He found that a private service provider responsible for vaccine distribution was compromising on quality to make profits. Despite immense pressure to manage the issue due to vested interests, he raised his voice based on the principles of public administration which he learnt during various training programmes attended across his career. He reported the issue to the appropriate vigilance authority and halted the contract to ensure citizen welfare.\nWhich one among the following principles of public administration was most strongly demonstrated by Mr. X's actions?", options: opts('Esprit de corps', 'Equity', 'Accountability', 'Delegation', 'C') },
  { category: 'Polity & Governance', text: "In a multi-ethnic district where both economic competition and historical grievances frequently led to community tensions, a flashpoint has arisen with a Government decision to allocate land for a waste management facility near a tribal hamlet, sparking protests by the tribal community, which claimed that the land was sacred and critical to their cultural identity. At the same time, urban residents and local industries supported the project, citing severe solid waste challenges and health concerns due to lack of a proper disposal site. The conflict has escalated with road blockades, social media campaigns, and allegations of police excesses.\nAs a responsible Government official, you are tasked with resolving the situation through mediation, ensuring a sustainable outcome that balances environmental needs, tribal rights, and urban public health.\nConsider the following statements with reference to the above:\n1. A successful conflict resolution process must begin with acknowledging the cultural concerns of the protesting tribal community before discussing technical alternatives.\n2. The Government should move ahead with the project without delay to address urban health concerns, which outweigh the sentiments of a small group.\n3. Creating a multi-stakeholder dialogue platform — including tribal leaders, environmental experts, and municipal representatives — to build mutual understanding and help de-escalate tensions.\n4. Conducting an independent Environmental and Social Impact Assessment (ESIA) and sharing findings transparently with both sides to facilitate evidence-based decision-making.\nWhich of the statements given above would contribute to the resolution process?", options: opts('1, 3 and 4 only', '2, 3 and 4 only', '1 and 2 only', '1, 2, 3 and 4', 'A') },
  { category: 'Polity & Governance', text: "Ms. X is a mid-level civil service official working in the urban development department of a major city. Recently, she was involved in approving a contract for a new community infrastructure project — a new community park. During the approval process, she received a piece of confidential information indicating that one of the shortlisted contractors had a history of poor workmanship and allegations of corruption in other cities, though nothing had been legally proven. The Head of the Department, Mr. Y, advised her not to disclose this information to the project committee or the public because it could delay the project and damage the city's reputation. However, Ms. X believed that withholding such information compromised transparency and public trust.\nWhat amongst the following should Ms. X do now?\n1. Immediately disclose the information to the project committee and the public\n2. Recommend removing the contractor from the shortlist to protect the project's integrity\n3. Propose a 'limited disclosure' to an oversight committee, while keeping the information confidential from the public for the time being\nSelect the answer using the code given below:", options: opts('1 and 2 only', '3 only', '2 and 3 only', '1, 2 and 3', 'D') },
  { category: 'Polity & Governance', text: "'X' was addressing a seminar on the meaning of the term 'law' as provided under Article 13, Part III of the Constitution of India. 'X' explained that the meaning of the term 'law' in the Constitution was very comprehensive. It included ordinances, orders and even rules and regulations. 'Y' pointed out that the term 'law' in Article 13 also included custom or usage having in the territory of India the force of law, to which 'X' was not convinced.\nBased on the above, select the correct conclusion from the options given below:", options: opts("'X' is correct in the interpretation of law, including the view on non-inclusion of custom.", "The view of 'Y' that 'law' included custom is not correct.", "The views of both 'X' and 'Y' are correct.", "The view of only 'Y' is correct.", 'B') },
  { category: 'Polity & Governance', text: "Consider the following statements with reference to the Constitution of India:\n1. There is no Article in the Constitution of India that specifies that the Constitution of India will be officially called the 'Constitution of India'.\n2. There is no Article in the Constitution of India that specifies that the Indian Independence Act, 1947 and the Government of India Act, 1935 stand repealed.\n3. There is no Article in the Constitution of India that mentions 26th January, 1950 as the date of the commencement of the Constitution of India.\nWhich one of the following conclusions based on the above statements is correct?", options: opts('All three statements are correct.', 'There is no correct statement.', 'There are two correct statements that include statement 3.', 'There is only one correct statement.', 'B') },
  { category: 'Polity & Governance', text: "Which of the following statements with regard to the persons with disabilities in India is/are correct?\n1. The Rights of Persons with Disabilities Act, an Act passed by the Parliament of India in 2018, mandates reservation in education and employment, places a legal duty on Governments to ensure accessibility and non-discrimination.\n2. The Sugamya Bharat Abhiyan focuses on achieving universal accessibility for Persons with Disabilities across three key domains — built infrastructure, transport systems and information and communication technology.\n3. The National Divyangjan Finance and Development Corporation (NDFDC) is a public sector organisation set up by the Ministry of Corporate Affairs as a not-for-profit company to promote entrepreneurship among Persons with Disabilities (PwDs).\nSelect the answer using the code given below:", options: opts('1 and 2', '2 only', '1 and 3', '1 only', 'A') },
  { category: 'Polity & Governance', text: "Consider the following statements about the provisions pertaining to the Scheduled Castes and the Scheduled Tribes in India:\n1. Provisions regarding the administration of the Tribal Areas in the States of Assam, Meghalaya, Tripura and Mizoram are given in the Fifth Schedule of the Constitution of India.\n2. Some tribes of India are entitled to exemption from paying Income Tax on certain incomes.\n3. The Constitution of India provides for reservation of seats in Panchayats for women belonging to the Scheduled Castes and the Scheduled Tribes.\nWhich one of the following conclusions based on the above statements is correct?", options: opts('There are two correct statements, that include statement 2.', 'There are two correct statements, that are statements 1 and 3.', 'There is only one correct statement.', 'All three statements are correct.', 'A') },
  { category: 'Polity & Governance', text: "Consider the following statements in respect of questions asked by the Members in the Parliament of India:\n1. Unstarred questions are those to which a Member desires an oral answer in the House.\n2. Starred questions are those to which a Member desires a written answer.\n3. No supplementary question can be asked on an unstarred question.\nWhich one of the following conclusions based on the above statements is correct?", options: opts('All the three statements are correct.', 'There are two correct statements, that include statement 2.', 'There is only one correct statement.', 'There is no correct statement.', 'C') },
  { category: 'Polity & Governance', text: "Consider the following statements about the Committee on the Welfare of Scheduled Castes and Scheduled Tribes of the Parliament of India:\n1. Although members of this Committee are elected from both Houses of Parliament, the Chairperson of this Committee is appointed by the Chairman of the Rajya Sabha.\n2. Twenty members are elected by the Rajya Sabha and ten members by the Lok Sabha.\n3. No Minister, except for the Union Minister of Social Justice and Empowerment, is eligible to be a member of this Committee.\n4. Members are elected for a fixed term of two years from the date they enter their office.\nWhich one of the following conclusions based on the above statements is correct?", options: opts('There are four correct statements.', 'There is only one correct statement, that is statement 2.', 'There are two correct statements, that include statement 1.', 'There is no correct statement.', 'D') },
  { category: 'Science & Technology', text: "Consider the following statements about Mission Sudarshan Chakra of India:\n1. It aims to enhance India's air defence, ballistic missile defence and aerial offensive capabilities.\n2. This Mission is being designed to enhance rapid, precise, and powerful defence responses, reinforcing India's strategic autonomy.\n3. One of the aims of this Mission is to cover all public places of India by an expanded nationwide security shield by 2035.\nWhich of the statements given above is/are correct?", options: opts('1, 2 and 3', '1 and 2 only', '2 and 3 only', '1 only', 'A') },
  { category: 'Geography', text: "Consider the following statements about river bridges connecting India with neighbouring countries:\n1. 'Maitri Setu', built over Feni river, connects Ramgarh in India with Sabroom in Bangladesh.\n2. Jhulaghat suspension bridge connects India with Myanmar.\n3. Mechi bridge and its approaches connect Panitanki Bypass in India with Kakarvitta in Nepal.\nWhich of the statements given above is/are correct?", options: opts('1 and 2', '2 and 3', '1 only', '3 only', 'D') },
  { category: 'Polity & Governance', text: "Which of the following statements about a Zero First Information Report (Zero FIR) under the Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023 is/are correct?\n1. A Zero FIR can be lodged at a police station, even though the place of commission of a cognizable offence is outside the territorial jurisdiction of that police station.\n2. The Officer-in-Charge of the police station where a Zero FIR has been lodged may, with the permission of the competent authority, initiate a preliminary enquiry.\n3. Under Zero FIR, it is obligatory for the informant to furnish information electronically.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '2 and 3 only', '1 only', '2 only', 'D') },
  { category: 'Polity & Governance', text: "With reference to the organisations under the Government of India, consider the following details:\n1. Central Economic Intelligence Bureau (CEIB) — To coordinate between various law enforcement agencies — Ministry of Home Affairs\n2. Serious Fraud Investigation Office (SFIO) — To investigate complex corporate frauds — Ministry of Finance\n3. Central Bureau of Investigation (CBI) — To preserve values in public life and ensure the health of the national economy — Ministry of Personnel, Public Grievances and Pension\nIn how many of the above rows are the given details correctly matched?", options: opts('1', '2', '3', 'None', 'A') },
  { category: 'International Relations', text: "Which of the following international conventions have not been ratified by India?\n1. Employment Policy Convention\n2. Abolition of Forced Labour Convention\n3. International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families\n4. Geneva Convention Relative to the Protection of Civilian Persons in Time of War\n5. Convention on Reduction of Statelessness\nSelect the answer using the code given below:", options: opts('2 and 4', '1 and 2', '3 and 4 only', '3, 4 and 5', 'B') },
  { category: 'Current Affairs', text: "Consider the following statements with respect to the AI Impact Summit, 2026 held in New Delhi:\n1. The Summit's intellectual framework was based on three foundational Sutras: People, Planning and Progress.\n2. The Preamble of the Summit stresses Democratising AI Resources, which acknowledges the Charter for Democratic Diffusion of AI as a binding framework to support locally relevant innovation and strengthen resilient AI ecosystems while respecting national laws.\n3. The New Delhi Declaration on AI Impact was structured around seven Chakras (Pillars), which included Access for Social Empowerment, AI for Science, and Secure and Trusted AI.\nWhich of the statements given above is/are correct?", options: opts('1, 2 and 3', '1 and 2 only', '2 and 3 only', '3 only', 'D') },
  { category: 'International Relations', text: "Which of the following connectivity projects is/are a part of cooperation between India and the ASEAN member countries?\n1. Kaladan Multi-Modal Transit Transport Project\n2. IMT Trilateral Highway\n3. Agartala–Akhaura Rail Line\nSelect the answer using the code given below:", options: opts('1 and 2', '2 and 3', '1 and 3', '2 only', 'A') },
  { category: 'International Relations', text: "Match List I with List II and select the answer using the code given below.\nList I (Project Supported by India)\nA. Mangdechhu Hydroelectric Project\nB. Restoration of Store Palace\nC. District Hospital at Dickoya\nD. Institute of Security and Law Enforcement Studies\nList II (Country)\n1. Maldives\n2. Afghanistan\n3. Bhutan\n4. Sri Lanka", options: opts('A-1 B-4 C-2 D-3', 'A-3 B-2 C-4 D-1', 'A-3 B-4 C-2 D-1', 'A-1 B-2 C-4 D-3', 'B') },
  { category: 'Science & Technology', text: "Which of the following items of defence hardware is/are manufactured in India?\n1. Su-30 MKI Fighter Jets\n2. T-90 MK-II Tanks\n3. Akula Class Submarine\nSelect the answer using the code given below:", options: opts('1 and 2', '1 and 3', '1 only', '2 only', 'A') },
  { category: 'International Relations', text: "Consider the following statements about platforms for multilateral co-operation:\n1. The 'Colombo Process' is a regional consultative process in which member states take binding decisions by consensus.\n2. The 'Abu Dhabi Dialogue' is a voluntary non-binding consultative process among Asian countries of labour origin and destination to facilitate regional cooperation on contractual labour mobility.\n3. The 'Global Forum for Migration and Development', created upon the proposal of a former UN Secretary General, is a voluntary forum whose decisions are non-binding in nature.\nWhich of the statements given above is/are correct?", options: opts('1, 2 and 3', '1 and 3 only', '2 and 3 only', '2 only', 'C') },
  { category: 'International Relations', text: "Consider the following UN organisations/agencies:\n1. World Food Programme\n2. United Nations Children's Fund\n3. United Nations High Commissioner for Refugees\n4. International Labour Organisation\nHow many of the above has/have been awarded the Nobel Prize twice?", options: opts('1', '2', '3', '4', 'A') },
  { category: 'International Relations', text: "Match List I with List II and select the answer using the code given below.\nList I (UN Peacekeeping Operation)\nA. UNMIL\nB. MINURCAT\nC. MINUSTAH\nD. UNMISET\nList II (Period of Operation)\n1. 2007–2010\n2. 2002–2005\n3. 2003–2018\n4. 2004–2017", options: opts('A-3 B-4 C-1 D-2', 'A-3 B-1 C-4 D-2', 'A-2 B-1 C-4 D-3', 'A-2 B-4 C-1 D-3', 'B') },
  { category: 'International Relations', text: "Match List I with List II and select the answer using the code given below.\nList I (BIMSTEC Centre / Establishment)\nA. BIMSTEC Cultural Industries Observatory\nB. BIMSTEC Energy Centre\nC. BIMSTEC Centre for Weather and Climate\nD. BIMSTEC Technology Transfer Facility\nList II (Location)\n1. NOIDA\n2. Bengaluru\n3. Colombo\n4. Thimphu", options: opts('A-3 B-2 C-1 D-4', 'A-3 B-1 C-2 D-4', 'A-4 B-2 C-1 D-3', 'A-4 B-1 C-2 D-3', 'C') },
  { category: 'Polity & Governance', text: "Which one of the following pairs is not correctly matched?\nIndian Army Corps — Headquarters\n(a) 3 Corps — Dimapur\n(b) 4 Corps — Tezpur\n(c) 14 Corps — Leh\n(d) 33 Corps — Srinagar", options: opts('3 Corps — Dimapur', '4 Corps — Tezpur', '14 Corps — Leh', '33 Corps — Srinagar', 'D') },
  { category: 'Polity & Governance', text: "Which of the following statements with respect to the Revamped Rashtriya Gram Swaraj Abhiyan (RGSA) is/are correct?\n1. The period of its implementation is 1st April, 2021 to 31st March, 2026.\n2. The key objective of the Revamped RGSA is to develop the governance capabilities of the Panchayati Raj Institutions to deliver on the Sustainable Development Goals.\n3. The share of the Central funding for the Revamped RGSA is 100% for all States and Union Territories.\nSelect the answer using the code given below:", options: opts('1 and 2', '2 only', '1 and 3', '2 and 3', 'B') },
  { category: 'International Relations', text: "Which of the following countries are members of the European Union?\n1. Belarus\n2. Poland\n3. Germany\n4. Switzerland\nSelect the answer using the code given below:", options: opts('1, 2 and 4', '1 and 4 only', '2 and 3', '2 and 4 only', 'C') },
  { category: 'International Relations', text: "Match List I with List II and select the answer using the code given below.\nList I (INTERPOL Notice)\nA. Silver Notice\nB. Blue Notice\nC. Black Notice\nD. Green Notice\nList II (Description)\n1. To seek information on unidentified bodies\n2. To collect additional information about a person's identity, location, or activities in relation to a criminal investigation\n3. To provide warning about a person's criminal activities where the person is considered to be a possible threat to public safety\n4. To identify and trace criminal assets", options: opts('A-3 B-1 C-2 D-4', 'A-3 B-2 C-1 D-4', 'A-4 B-2 C-1 D-3', 'A-4 B-1 C-2 D-3', 'C') },
  { category: 'Environment & Ecology', text: "Which of the following statements in relation to NIRANTAR (National Institute for Research and Application of Natural Resources to Transform, Adapt and Build Resilience), a platform of institutions under the Ministry of Environment, Forest and Climate Change, is/are correct?\n1. Ecosystem Survey and Analysis is a vertical under this platform, the lead institute of which is Botanical Survey of India, Kolkata.\n2. Research and Management of Ecosystem Services is a vertical under this platform, the lead institute of which is Central Zoo Authority, New Delhi.\n3. Capacity Development Support is a vertical under this platform, the lead institute of which is Indian Institute of Forest Management, Bhopal.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '1 and 3 only', '2 only', '3 only', 'D') },
  { category: 'International Relations', text: "The Chancellor of the Federal Republic of Germany visited India in January, 2026. Which of the following is/are not correct in terms of outcomes of this visit?\n1. Signing of a Memorandum of Understanding between the All India Institute of Ayurveda and the University of Hamburg.\n2. Signing of a Memorandum of Understanding on Youth Hockey Development between Hockey India and the German Hockey Federation.\n3. Establishment of a bilateral dialogue mechanism on the Indo-Pacific.\n4. Opening of an Honorary Consul of Germany in Lucknow.\nSelect the answer using the code given below:", options: opts('2 and 3', '1 and 4', '3 and 4', '1 only', 'B') },
  { category: 'Science & Technology', text: "Which of the following statements about DHRUV64 is/are correct?\n1. It is the third chip fabricated under the DIR-V Programme with an overall aim to enable the creation of microprocessors for India.\n2. It is India's first homegrown 10 GHz, 64-bit dual core microprocessor.\nSelect the answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'C') },
  { category: 'Science & Technology', text: "The Bureau of Indian Standards (BIS) recently introduced a national standard to test and assess bomb disposal system. Which of the following statements with regard to this system is/are correct?\n1. The new standard is known as IS 19445 : 2025.\n2. It will improve interoperability of equipment across agencies.\n3. It was developed by TBRL, DRDO in collaboration with the 30th Central Scientific Research Institute, Russia.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '2 and 3 only', '1 and 2 only', '1 only', 'D') },
  { category: 'Science & Technology', text: "'X', born in the UK, was conferred the Nobel Prize in 2025. He was a professor in an American university when this prize was announced. Identify 'X'.", options: opts('Michel H. Devoret', 'Richard Robson', 'John Clarke', 'Joel Mokyr', 'C') },
  { category: 'Miscellaneous', text: "Which of the following statements with regard to the Grand Slam Tennis Tournaments is/are correct?\n1. The tournaments have a shared governance structure establishing the partnership among the four Grand Slam tournaments.\n2. They are open for entry to all internationally ranked tennis players above the age of 14.\n3. There is a limitation on the number of 'Wild Cards' a player may receive to compete in a Grand Slam Tournament.\nSelect the answer using the code given below:", options: opts('1 and 2 only', '2 and 3 only', '1 only', '1, 2 and 3', 'A') },
  { category: 'Science & Technology', text: "Which one of the following pairs of semiconductor plants in India and their locations is not correctly matched?", options: opts('CG Power and Industrial Solutions Pvt. Ltd. in partnership with Renesas Electronics and STARS Microelectronics — Gujarat', 'Tata Semiconductor Assembly and Test Pvt. Ltd. — Assam', 'HCL–Foxconn Joint Venture India Chip Ltd. — Madhya Pradesh', 'SicSem Pvt. Ltd. — Odisha', 'C') },
  { category: 'Science & Technology', text: "Which of the following statements with regard to India's indigenous new high resolution weather model, the 'Bharat Forecast System', is/are correct?\n1. Its objective is to generate forecasts at the Panchayats cluster level.\n2. It was developed by IIT Delhi.\nSelect the answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'A') },
  { category: 'Art & Culture', text: "Consider the following statements with regard to the film Boong:\n1. The film has recently won the British Academy of Film and Television Arts (BAFTA) Award in the Children's and Family Film category.\n2. The film is directed by Lakshmipriya Devi.\n3. This is the first Indian film to win a BAFTA award in the Children's and Family Film category.\nWhich of the statements given above is/are correct?", options: opts('1, 2 and 3', '2 and 3 only', '1 and 2 only', '3 only', 'A') },
  { category: 'Science & Technology', text: "Which of the following statements regarding the features of blockchain technology are correct?\n1. Records stored in the database may be made visible to relevant stakeholders without risk of alteration.\n2. Copies of the entire database are stored on multiple computers on a network, syncing within seconds.\n3. Consortium blockchain is a blend of public and private blockchains allowing selective data access.\n4. Mathematical algorithms make it impossible to change or delete any data once recorded and accepted.\nSelect the answer using the code given below:", options: opts('1 and 3', '2 and 4 only', '1, 2 and 4', '1 and 4 only', 'C') },
  { category: 'Economy', text: "An e-commerce revenue model where the seller has control over pricing but doesn't keep products in stock and instead transfers customer orders and shipment details to a third-party supplier, who then ships the goods directly to the customer, is called:", options: opts('Dropshipping Model', 'Affiliate Revenue Model', 'Transaction Fee Revenue Model', 'Agency Revenue Model', 'A') },
  { category: 'Economy', text: "Which one of the following correctly represents the three key sub-indices of the Financial Inclusion Index (FI-Index) of the Reserve Bank of India (RBI)?", options: opts('Credit access, Insurance depth and Pension coverage', 'Banking access, GDP contribution and Financial literacy', 'Access, Usage and Quality', 'Access, Affordability and Transparency', 'C') },
  { category: 'Economy', text: "Which one of the following best describes the key objective of India's 'Open Network for Digital Commerce' (ONDC) initiative?", options: opts('To allow government control over all digital commerce transactions', 'To replace private e-commerce players', 'To break the dominance of large e-commerce platforms by enabling interoperability across networks', 'To mandate UPI-based payments for all online transactions', 'C') },
  { category: 'Economy', text: "Which one of the following statements about Unified Payments Interface (UPI) and Central Bank Digital Currency (Digital Rupee) is not correct?", options: opts('UPI is a real-time payment system but Digital Rupee is akin to sovereign paper currency.', 'In case of UPI, settlement for end users happens instantly as the money gets immediately debited or credited but in case of Digital Rupee, there is no settlement as the wallet balance gets transferred to another wallet.', 'UPI transactions are recorded by banks and reflected in bank statements but in case of Digital Rupee, no data is captured in bank statements as transactions are from one wallet to another.', 'In both the cases (UPI and Digital Rupee), the liability lies with the users and their respective banks.', 'D') },
  { category: 'Economy', text: "Which of the following statements about Real-World Asset (RWA) Tokenization are correct?\n1. Tokenization is the process of turning real world assets into digital tokens using blockchain technology.\n2. Tokenization of real world assets offers 24×7 access, promoting financial inclusion.\n3. Tokenization of real world assets will allow the access to high growth investment opportunities for individuals in India.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '2 and 3 only', '1 and 2 only', '1 and 3 only', 'A') },
  { category: 'Economy', text: "A bond whose proceeds are used only to finance or refinance a combination of both environmental and social projects is called:", options: opts('Green Bond', 'Social Bond', 'Sustainability Bond', 'Sovereign Bond', 'C') },
  { category: 'Economy', text: "Which of the following statements about M1xchange's role in Micro, Small & Medium Enterprises (MSMEs) financing is/are correct?\n1. M1xchange provides collateral based loans to MSMEs.\n2. M1xchange facilitates discounting of invoices and Bills of Exchange for MSMEs.\n3. M1xchange functions as a credit rating agency for MSMEs.\nSelect the answer using the code given below:", options: opts('1, 2 and 3', '2 only', '2 and 3 only', '1 only', 'B') },
  { category: 'Economy', text: "Which one of the following best describes the \"Crowding Out Effect\" in the context of fiscal policy?", options: opts('A situation where private investment increases due to increased Government spending.', 'A situation where Government borrowing leads to higher interest rates, which reduces private investment.', 'A situation where an increase in taxes leads to increased private sector investment.', 'A situation where Government spending has no impact on aggregate demand.', 'B') },
  { category: 'Economy', text: "Which of the following statements about Rare Earth Elements (REEs) and Critical Minerals is/are correct?\n1. Modern technological innovations including Artificial Intelligence, robotics and space exploration extensively utilise Rare Earth Elements (REEs).\n2. China has the highest share in mining of REEs followed by India.\n3. The Government of India launched the National Critical Mineral Mission (NCMM) in 2025 to establish a robust framework for self-reliance in the critical mineral sector.\n4. Rare Earth Elements are a set of 13 metallic elements.\nSelect the answer using the code given below:", options: opts('1 and 3 only', '3 only', '1, 3 and 4', '1, 2 and 4', 'A') },
  { category: 'Economy', text: "Which of the following statements about insurance in aviation sector is/are correct?\n1. \"Aviation Hull Insurance\" covers the physical aircraft, including the body, engine and on-board equipment.\n2. Under the Montreal Convention, adopted in 1999 by over 130 countries, including India, airlines are strictly liable to pay compensation to the deceased family/nominee of every deceased passenger without requiring the family to prove fault.\nSelect the answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'C') },
  { category: 'Economy', text: "Which of the following statements about crowdfunding is/are correct?\n1. Crowdfunding is solicitation of funds from small amount from multiple investors through a web-based platform or social networking site for a specific project.\n2. Small and Medium Enterprises (SMEs) are able to raise funds at lower cost of capital without undergoing rigorous procedures.\nSelect the answer using the code given below:", options: opts('1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2', 'A') },
  { category: 'Economy', text: "Consider the following Committees in India and the following details:\n1. R.N. Malhotra Committee — Comprehensive reforms of Insurance sector in India — IRDAI\n2. L.C. Gupta Committee — Preparing a roadmap for introduction of derivatives trading in India — SEBI\n3. Urijit R. Patel Committee — Preparing a roadmap for reforming bank lending to the housing sector — RBI\n4. Y.H. Malegam Committee — Preparing a roadmap for reforming Microfinance sector in India — RBI\nIn which of the above rows are all the details correctly matched?", options: opts('2 only', '2 and 3', '1, 3 and 4', '2 and 4', 'D') },
  { category: 'Economy', text: "Consider the following statements about the Non-Banking Financial Companies (NBFCs) in India:\n1. NBFCs cannot accept demand deposits.\n2. All the NBFCs operating in India have to be registered with the RBI.\n3. NBFCs form part of the payment and settlement system and can issue cheque drawn on itself.\n4. Deposit insurance facility of Deposit Insurance and Credit Guarantee Corporation (DICGC) is not available to the depositors of deposit taking NBFCs.\nWhich of the statements given above is/are correct?", options: opts('1 and 4', '1, 2 and 3', '4 only', '2, 3 and 4', 'A') },
  { category: 'Economy', text: "Consider the following statements about Multidimensional Poverty Index (MPI):\n1. MPI is calculated using Alkire-Foster methodology.\n2. MPI calculated by NITI Aayog has a total of twelve indicators.\n3. Maternal Health and Bank Account are common indicators in the MPI of NITI Aayog and MPI of United Nations Development Programme (UNDP).\nWhich of the statements given above is/are correct?", options: opts('1 and 2 only', '1, 2 and 3', '1 and 3 only', '2 only', 'A') },
]

async function main() {
  console.log('Seeding UPSC Prelims GS1 2026 paper...')

  const examType = await prisma.examType.upsert({
    where: { code: 'PRELIMS_GS1' },
    update: {},
    create: { code: 'PRELIMS_GS1', name: 'Prelims General Studies I' },
  })

  const paper = await prisma.questionPaper.upsert({
    where: { examTypeId_year: { examTypeId: examType.id, year: 2026 } },
    update: {},
    create: {
      year: 2026,
      examTypeId: examType.id,
      title: 'UPSC CSE Prelims 2026 - General Studies I',
    },
  })

  const existing = await prisma.question.findMany({ where: { questionPaperId: paper.id }, select: { id: true } })
  const existingIds = existing.map((q) => q.id)
  await prisma.option.deleteMany({ where: { questionId: { in: existingIds } } })
  await prisma.question.deleteMany({ where: { id: { in: existingIds } } })

  const categoryCache = new Map<string, number>()
  async function categoryId(name: string): Promise<number> {
    if (categoryCache.has(name)) return categoryCache.get(name)!
    const category = await prisma.category.upsert({
      where: { name },
      update: {},
      create: { name },
    })
    categoryCache.set(name, category.id)
    return category.id
  }

  let count = 0
  for (const q of questions) {
    const catId = await categoryId(q.category)
    await prisma.question.create({
      data: {
        text: q.text,
        categoryId: catId,
        questionPaperId: paper.id,
        options: {
          create: q.options,
        },
      },
    })
    count++
  }

  console.log(`Seeded ${count} questions for UPSC Prelims GS1 2026.`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
